### ISSUE TITLE
部署几天后重启出现 docker fatal error: fault 但容器作为透明网关仍正常运行

### ISSUE THREAD

**Issue by exxtremecn** [SuLingGG/OpenWrt-Docker#67]
遇到个奇怪的问题，部署 OpenWrt-Docker 容器几天后，重启查看 docker ps 报错

uefi-x86:~:# docker ps
unexpected fault address 0x556c942340a0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x556c942340a0 pc=0x556c942340a0]

goroutine 1 [running, locked to thread]:
runtime.throw({0x556c94d0cbc1?, 0x556c9420215b?})
	/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc00025f6d8 sp=0xc00025f6a8 pc=0x556c93aa2371
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:825 +0x2ec fp=0xc00025f728 sp=0xc00025f6d8 pc=0x556c93ab7b4c
github.com/docker/cli/vendor/github.com/moby/buildkit/frontend/gateway/pb.init()
	/go/src/github.com/docker/cli/vendor/github.com/moby/buildkit/frontend/gateway/pb/caps.go:5 fp=0xc00025f730 sp=0xc00025f728 pc=0x556c942340a0
runtime.doInit(0x556c960bdd20)
	/usr/local/go/src/runtime/proc.go:6222 +0x128 fp=0xc00025f860 sp=0xc00025f730 pc=0x556c93ab19c8
runtime.doInit(0x556c960c14c0)
	/usr/local/go/src/runtime/proc.go:6199 +0x71 fp=0xc00025f990 sp=0xc00025f860 pc=0x556c93ab1911
runtime.doInit(0x556c960c5840)
	/usr/local/go/src/runtime/proc.go:6199 +0x71 fp=0xc00025fac0 sp=0xc00025f990 pc=0x556c93ab1911
runtime.doInit(0x556c960c9ac0)
	/usr/local/go/src/runtime/proc.go:6199 +0x71 fp=0xc00025fbf0 sp=0xc00025fac0 pc=0x556c93ab1911
runtime.doInit(0x556c960b65e0)
	/usr/local/go/src/runtime/proc.go:6199 +0x71 fp=0xc00025fd20 sp=0xc00025fbf0 pc=0x556c93ab1911
runtime.doInit(0x556c960be6e0)
	/usr/local/go/src/runtime/proc.go:6199 +0x71 fp=0xc00025fe50 sp=0xc00025fd20 pc=0x556c93ab1911
runtime.doInit(0x556c960bcee0)
	/usr/local/go/src/runtime/proc.go:6199 +0x71 fp=0xc00025ff80 sp=0xc00025fe50 pc=0x556c93ab1911
runtime.main()
	/usr/local/go/src/runtime/proc.go:233 +0x1d4 fp=0xc00025ffe0 sp=0xc00025ff80 pc=0x556c93aa4a54
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00025ffe8 sp=0xc00025ffe0 pc=0x556c93ad2821

<img width="960" alt="docker-fatal-error" src="https://user-images.githubusercontent.com/68555988/196595672-e85bc31e-652a-4c28-991a-6a3d561cccac.png">

但 OpenWrt-Docker 容器作为透明网关仍然正常运行
<img width="960" alt="docker-still-run2" src="https://user-images.githubusercontent.com/68555988/196596423-0318adcb-2931-4178-aa09-9e7687b850e6.png">

硬件和 OS 相关
CPU: Intel Core 2 Duo P8600 (2) @ 1.600GHz 
Memory: 250MiB / 1878MiB 
OS: x86_64 "Armbian 22.08.5 Bullseye"
Kernel: 5.15.73-x86 
<img width="960" alt="docker-hardware-os" src="https://user-images.githubusercontent.com/68555988/196595790-a8679a37-f52d-4a08-9b79-45ef3d923f8b.png">

docker 安装方法：官方脚本
https://docs.docker.com/engine/install/debian/#install-using-the-convenience-script
# curl -fsSL https://get.docker.com -o get-docker.sh
# sh get-docker.sh

现在无法查看 / 停止容器，也无法部署新的容器，目前看只能卸载 docker 重新安装，然后重新部署

**Comment by exxtremecn** [comment]
问题解决，armbian x86 在 reboot 后会报错，但数据没有损坏， 关机后再开机就能恢复，然后就可以部署新容器了

<img width="960" alt="armbian-docker-portainer" src="https://user-images.githubusercontent.com/68555988/196897760-f3cf2252-7c76-40a2-b173-28ff0292259a.png">
